// normalized DIM data buttons patch
import { state, setState, setRows, updateTag } from './state.js';
import { connectBungie, initializeBungieSync, scheduleSemiLiveRefresh, shouldRefreshOnFocus, syncBungieInventory } from './data/bungie-sync.js?v=clean62';
import { isSignedIn } from './data/bungie-auth.js?v=clean62';
import { syncDimTags, clearDimApiKey } from './data/dim-tags.js?v=1.6';

const setStatus = (status) => setState({ status });
const hasRows = () => state.rows.length > 0;
const ROW_CACHE_KEY = 'd2aa_clean_rows_v1';
const LIVE_REFRESH_MS = 60000;
const ITEM_FEED_CHECK_MS = 45000;
const LIVE_MIN_GAP_MS = 20000;
const MIN_FEED_SPINNER_MS = 1400;
let lastLiveRefreshAt = 0, liveRefreshTimer = null, itemFeedPollTimer = null, feedPollingClearTimer = null, feedPollingStartedAt = 0, controlsBound = false, activeSyncReason = '';
const dataButtonHtml = (icon,label,detail)=>`<span>${icon}</span><b>${label}</b><small>${detail}</small>`;
function bindBungieControls(){if(controlsBound)return;controlsBound=true;refreshLoginState();ensureDimSyncButton();document.addEventListener('click',(event)=>{const button=event.target.closest?.('#bungieLoginBtn,#bungieSyncBtn,#refreshBtn,#dimTagSyncBtn,#dimTagResetBtn');if(!button)return;if(button.id==='bungieLoginBtn'){event.preventDefault();connectBungie();return;}if(button.id==='bungieSyncBtn'){event.preventDefault();runSync('manual-sync');return;}if(button.id==='refreshBtn'){event.preventDefault();runSync('refresh-button');return;}if(button.id==='dimTagSyncBtn'){event.preventDefault();if(!button.disabled)runDimTagSync(button);return;}if(button.id==='dimTagResetBtn'){event.preventDefault();clearDimApiKey();setStatus('DIM API key/token cleared from this browser.');updateDimSyncAvailability();}});window.addEventListener('d2aa:bungie-sync-request',(event)=>{const detail=event.detail||{};runSync(detail.reason||'app-request',Boolean(detail.background));});}
async function runSync(reason,background=false){if(activeSyncReason)return;if(!isSignedIn()){refreshLoginState();return setStatus('Connect your Destiny account before syncing armor.');}activeSyncReason=reason;try{const result=await syncBungieInventory({setStatus,setRows,reason,background});refreshLoginState();if(result){lastLiveRefreshAt=Date.now();scheduleSemiLiveRefresh({setStatus,setRows,hasRows,delay:LIVE_REFRESH_MS});}}finally{activeSyncReason='';}}
async function runDimTagSync(button){const original=button?.innerHTML||'';if(button)button.innerHTML=dataButtonHtml('⌁','Syncing DIM Tags...','Read-only pull');try{const result=await syncDimTags({setStatus});let changed=0;state.rows.forEach((row)=>{const tag=result.tags?.[row.InstanceId||row.Id]||result.tags?.[row.Id];if(tag&&tag!==row.Tag){updateTag(row.Id,tag);changed+=1;}});setStatus(`DIM tag sync complete. Applied ${changed} matching tags from ${result.count} DIM-tagged items.`);}catch(error){console.error('D2AA DIM tag sync failed',error);setStatus(error.message||String(error));}finally{if(button)setTimeout(()=>{button.innerHTML=original;updateDimSyncAvailability();},1200);}}
function ensureDimSyncButton(){if(document.getElementById('dimTagSyncBtn'))return;const sync=document.getElementById('bungieSyncBtn');const host=sync?.parentElement;if(!host)return;const button=document.createElement('button');button.id='dimTagSyncBtn';button.type='button';button.className=`${sync?.className||'option-button'} data-secondary-card`;host.appendChild(button);const reset=document.createElement('button');reset.id='dimTagResetBtn';reset.type='button';reset.className=`${sync?.className||'option-button'} data-secondary-card data-reset-card`;reset.innerHTML=dataButtonHtml('⟲','Reset DIM Key','Clear local DIM API token');host.appendChild(reset);updateDimSyncAvailability();}
function updateDimSyncAvailability(){const button=document.getElementById('dimTagSyncBtn');if(!button)return;if(canRunLiveDimSync()){button.disabled=false;button.title='';button.innerHTML=dataButtonHtml('⌁','Sync DIM Tags','Pull favorite/keep/junk/infuse/archive');}else{button.disabled=true;button.title='DIM blocks automatic app registration from GitHub Pages.';button.innerHTML=dataButtonHtml('⌁','DIM Tags Unavailable','Use DIM CSV import for tags');}}
function canRunLiveDimSync(){const host=window.location.hostname||'localhost';const hasKey=Boolean(localStorage.getItem('d2aa_dim_api_key_v1')||localStorage.getItem('dimApiKey')||window.D2AA_DIM_API_KEY);const localHost=host==='localhost'||host==='127.0.0.1';return hasKey||localHost;}
function refreshLoginState(){const login=document.getElementById('bungieLoginBtn');const sync=document.getElementById('bungieSyncBtn');const signedIn=isSignedIn();if(login){const label=login.querySelector('b');const detail=login.querySelector('small');if(label)label.textContent=signedIn?'Destiny Account Connected':'Connect Destiny Account';if(detail)detail.textContent=signedIn?'Session remembered; refresh uses Bungie token':'Bungie OAuth login';login.disabled=false;}if(sync)sync.disabled=false;document.body.classList.toggle('bungie-signed-in',signedIn);updateDimSyncAvailability();}
async function bootBungieSidecar(){bindBungieControls();try{await initializeBungieSync({setStatus,setRows,hasRows});refreshLoginState();}catch(error){console.error('D2AA clean Bungie sidecar failed',error);setStatus(error.message||String(error));refreshLoginState();}}
bootBungieSidecar();