import { state, subscribe, setState, updateTag, dismissRecent, getFilteredRows, loadCachedRows, clearCache, loadSettings, normalizeClassFilter, rowMatchesClass, writeJson } from '../src-clean/state.js';
import { CLASS_ORDER, SLOT_ORDER, STAT_KEYS, STAT_LABELS, STAT_ICONS, TAGS, STORAGE_KEYS } from '../src-clean/constants.js';
import { applyDuplicateGroups } from '../src-clean/data/duplicate-groups.js?v=1.64';
import { runItemAction, runGroupPull } from '../src-clean/data/actions.js';
import { saveBungieInventory } from '../src-clean/data/inventory-cache.js';
import { getActiveFeedRows } from '../src-clean/data/feed-state.js';
import { openCompareModal } from '../src-clean/render/compare-modal.js?v=compare-renderers-1';

const els = {};
let lastGroupedRows = [];
let openTagMenu = null;
const collapsedSlots = new Set();
const BONUS_ORDER = ['masterwork', 'mod', 'artifice', 'other'];
const ARCHETYPE_NAMES = new Set(['paragon','grenadier','specialist','brawler','bulwark','gunner']);

function boot(){ cacheEls(); loadSettings(); forceSingleClassDefault(); bindEvents(); subscribe(handleStateUpdate); loadCachedRows(); render(); }
function handleStateUpdate(_,detail={}){ if(detail.statusOnly){ if(els.statusText) els.statusText.textContent=state.status; return; } render(); }
function cacheEls(){ ['statusText','searchBox','refreshBtn','menuBtn','commandPanel','classToggle','gridView','tableView','tableBody','emptyState','summaryShown','summaryCached','summaryGroups','summaryRecent','summaryClasses','activeChips','csvFile','uploadCsvBtn','restoreCacheBtn','clearCacheBtn','classFilter','slotFilter','rarityFilter','sortBy','duplicateTolerance','duplicateToleranceOut','feedList','feedCount','feedToggle','itemFeed'].forEach(id=>els[id]=document.getElementById(id)); }
function forceSingleClassDefault(){ const cls = normalizeClassFilter(state.filters.class); if(cls === 'all') setState({ filters:{...state.filters, class:'Warlock'} }); }
function bindEvents(){
  els.searchBox?.addEventListener('input',()=>setState({search:els.searchBox.value}));
  els.menuBtn?.addEventListener('click',()=>setOptionsOpen(!els.commandPanel?.classList.contains('is-open')));
  document.addEventListener('pointerdown',(e)=>{ if(openTagMenu && !openTagMenu.contains(e.target) && !e.target.closest('[data-tag-button]')) closeTagMenu(); if(!document.body.classList.contains('options-open')) return; if(els.commandPanel?.contains(e.target)||els.menuBtn?.contains(e.target)) return; setOptionsOpen(false); });
  document.addEventListener('keydown',(e)=>{ if(e.key==='Escape'){ closeTagMenu(); setOptionsOpen(false); } });
  els.classToggle?.querySelectorAll('[data-class-filter]').forEach(btn=>btn.addEventListener('click',()=>setClassFilter(btn.dataset.classFilter)));
  els.classFilter?.addEventListener('change',()=>setClassFilter(els.classFilter.value));
  els.slotFilter?.addEventListener('change',()=>setState({filters:{...state.filters, slot:els.slotFilter.value}}));
  els.rarityFilter?.addEventListener('change',()=>setState({filters:{...state.filters, rarity:els.rarityFilter.value}}));
  els.sortBy?.addEventListener('change',()=>setState({sortBy:els.sortBy.value}));
  els.duplicateTolerance?.addEventListener('input',()=>setState({duplicateTolerance:Number(els.duplicateTolerance.value||5)}));
  els.restoreCacheBtn?.addEventListener('click',()=>loadCachedRows()||setState({status:'No cached rows found. Bungie cache restores automatically at startup.'}));
  els.clearCacheBtn?.addEventListener('click',clearCache);
  els.feedToggle?.addEventListener('click',()=>{ const open=!els.itemFeed.classList.contains('is-open'); els.itemFeed.classList.toggle('is-open',open); document.body.classList.toggle('feed-open',open); writeJson(STORAGE_KEYS.feedOpen,open); });
  document.addEventListener('click',handleDocumentClick);
}
function setOptionsOpen(open){ els.commandPanel?.classList.toggle('is-open',open); document.body.classList.toggle('options-open',open); els.menuBtn?.setAttribute('aria-expanded',String(open)); }
function setClassFilter(className){ setState({filters:{...state.filters, class:normalizeClassFilter(className)}}); }
function render(){
  document.body.dataset.theme='ingame';
  if(els.statusText) els.statusText.textContent=state.status;
  if(els.searchBox) els.searchBox.value=state.search;
  if(els.sortBy) els.sortBy.value=state.sortBy;
  if(els.duplicateTolerance) els.duplicateTolerance.value=state.duplicateTolerance;
  if(els.duplicateToleranceOut) els.duplicateToleranceOut.textContent=`±${state.duplicateTolerance}`;
  syncFilters(); syncClassToggle();
  const grouped = applyDuplicateGroups(state.rows,state.duplicateTolerance).map(addGrade);
  lastGroupedRows = grouped;
  const filtered = getFilteredRowsFrom(grouped).filter(r=>normalizeClassFilter(state.filters.class)!=='all' ? rowMatchesClass(r,state.filters.class) : false);
  renderGrid(filtered); renderFeed(grouped); updateSummary(grouped,filtered); renderChips();
  if(els.emptyState) els.emptyState.hidden = state.rows.length>0;
}
function renderGrid(rows){ if(!els.gridView) return; const cls=normalizeClassFilter(state.filters.class); const bySlot=SLOT_ORDER.map(slot=>[slot,rows.filter(r=>r.Slot===slot)]).filter(([_,items])=>items.length); els.gridView.innerHTML=bySlot.map(([slot,items])=>{ const collapsed=collapsedSlots.has(slot); return `<section class="slot-section ${collapsed?'is-collapsed':''}" data-slot="${h(slot)}"><button type="button" class="slot-heading" data-collapse-slot="${h(slot)}" aria-expanded="${!collapsed}"><span class="slot-caret" aria-hidden="true">${caretIcon(collapsed)}</span><span>${h(cls)}</span><strong>${h(slot)}</strong><b>${items.length}</b></button><div class="card-grid">${collapsed?'':items.map(renderCard).join('')}</div></section>`; }).join(''); }
function renderCard(row){
  const loc=locationText(row); const tag=row.Tag||''; const grade=gradeFor(row); const group=groupLabel(row); const name=displayName(row); const groupClass=groupColorClass(row); const master=row.IsMasterworked?' is-masterworked':'';
  return `<article class="armor-card rarity-${rarityClass(row.Rarity)} ${groupClass}${master}" data-id="${h(row.Id)}" data-group="${h(row.GroupActionKey||'')}">
    <div class="card-title"><img class="item-icon" src="${h(row.IconUrl||row.Icon||'')}" alt="" title="${h(row.OrnamentName?`Appearance: ${row.OrnamentName}`:name)}"/><div class="tier-rail">${tierMarks(row).join('')}</div><div class="title-copy"><strong title="${h(name)}">${h(name)}</strong><div class="meta-line"><button type="button" class="tag-chip" data-tag-button data-id="${h(row.Id)}">${tag?tagLabel(tag):'+'}</button>${row.IsLocked?lockChip(row):''}${locationChip(loc,row)}<span class="grade-chip grade-${grade.letter}" title="Rank ${grade.letter} · ${grade.score}">${grade.letter}</span></div></div>${row.Is_Dupe?`<button type="button" class="group-badge ${groupClass}" data-compare-group="${h(row.GroupActionKey)}" title="Compare group ${h(group)}">${h(group)}</button>`:''}<div class="power-badge">${h(row.Power||row.Light||'')}</div></div>
    <div class="card-body"><aside class="card-side"><div class="archetype">${archetypeIcon(row)}<b>${h(row.Archetype||'—')}</b></div>${renderArmorBonuses(row)}</aside><div class="stat-bars">${STAT_KEYS.map(k=>renderStat(row,k)).join('')}${renderTotal(row)}</div></div>
  </article>`;
}
function renderStat(row,key){ const model=statModel(row,key); return `<div class="stat-row" title="${h(STAT_LABELS[key])}: base ${model.base}${model.parts.length?`, ${model.parts.map(p=>`+${p.value} ${p.type}`).join(', ')}`:''}"><img src="${h(STAT_ICONS[key])}" alt="${h(STAT_LABELS[key])}"/><div class="bar"><span class="bar-base" style="width:${Math.min(100,model.base)}%"></span>${renderBonusSegments(model.base,model.parts)}</div><b>${pad(model.current)}</b></div>`; }
function renderBonusSegments(base,parts){ let left=Math.min(100,base); return parts.map(part=>{ const width=Math.max(0,Math.min(100-left,part.value)); const html=`<span class="bar-bonus bonus-${part.type}" title="+${part.value} ${h(part.type)}" style="left:${left}%;width:${width}%"></span>`; left+=width; return html; }).join(''); }
function renderTotal(row){ const base=baseTotal(row); const parts=totalBonusParts(row); const bonusTotal=parts.reduce((sum,p)=>sum+n(p.value),0); const absolute=currentTotal(row); const calc=`<span class="base-total">${base}</span>${parts.map(p=>`<span class="bonus-total bonus-${p.type}" title="${h(p.type)} bonus">+${p.value}</span>`).join('')}`; return `<div class="stat-total" title="Total calculation: base ${base}${parts.length?`, ${parts.map(p=>`+${p.value} ${p.type}`).join(', ')}`:''}. Absolute total: ${absolute}." style="grid-template-columns:1fr auto;gap:8px;align-items:end;"><div class="total-left" style="grid-column:1/2;display:grid;gap:3px;min-width:0;"><span class="total-label" style="grid-column:auto;">Total</span><div class="total-value" style="grid-column:auto;justify-self:start;font-size:14px;line-height:1;">${calc}</div></div><b class="absolute-total" style="grid-column:2/3;font-variant-numeric:tabular-nums;text-align:right;font-size:19px;line-height:1;color:#fff;min-width:34px;">${absolute}</b></div>`; }
function renderFeed(rows){ const active=getActiveFeedRows(rows).map(addGrade); if(els.feedCount) els.feedCount.textContent=String(active.length); if(!els.feedList) return; els.feedList.innerHTML=active.map(row=>{ const group=groupLabel(row); const groupClass=groupColorClass(row); const loc=locationText(row); return `<article class="feed-card rarity-${rarityClass(row.Rarity)} ${groupClass} ${row.IsMasterworked?'is-masterworked':''}" data-id="${h(row.Id)}"><img src="${h(row.IconUrl||row.Icon||'')}" alt=""/><div class="tier-rail">${tierMarks(row).join('')}</div><div><strong>${h(displayName(row))}</strong><span class="feed-meta"><button type="button" class="tag-chip" data-tag-button data-id="${h(row.Id)}">${row.Tag?tagLabel(row.Tag):'+'}</button>${row.IsLocked?lockChip(row):''}${locationChip(loc,row)}<b class="grade-chip grade-${gradeFor(row).letter}" title="Rank ${gradeFor(row).letter}">${gradeFor(row).letter}</b></span><small>${h(row.Slot)} · ${h(row.Archetype||'—')} · ${h(row.Power||row.Light||'')}</small></div>${row.Is_Dupe?`<button type="button" class="group-badge ${groupClass}" data-compare-group="${h(row.GroupActionKey)}">${h(group)}</button>`:''}<button type="button" class="dismiss" data-dismiss="${h(row.Id)}">×</button></article>`; }).join(''); }
function handleDocumentClick(e){ const tagButton=e.target.closest('[data-tag-button]'); if(tagButton){ e.preventDefault(); e.stopPropagation(); openTagPicker(tagButton, tagButton.dataset.id); return; } const tagChoice=e.target.closest('[data-tag-choice]'); if(tagChoice){ e.preventDefault(); e.stopPropagation(); updateTag(tagChoice.dataset.id, tagChoice.dataset.tag || ''); closeTagMenu(); return; } const collapse=e.target.closest('[data-collapse-slot]'); if(collapse){ const slot=collapse.dataset.collapseSlot; collapsedSlots.has(slot)?collapsedSlots.delete(slot):collapsedSlots.add(slot); render(); return; } const cmp=e.target.closest('[data-compare-group]'); if(cmp){ openGroupCompare(cmp.dataset.compareGroup); return; } const action=e.target.closest('[data-action]'); if(action){ handleAction(action.dataset.action,action); return; } const dismiss=e.target.closest('[data-dismiss]'); if(dismiss){ dismissRecent(dismiss.dataset.dismiss); return; } }
function openTagPicker(button,id){ closeTagMenu(); const current=state.tags[id]||state.rows.find(r=>String(r.Id)===String(id))?.Tag||''; const menu=document.createElement('div'); menu.className='tag-menu'; menu.innerHTML=TAGS.filter(t=>t.picker!==false).map(t=>`<button type="button" class="tag-menu-item ${current===t.value?'is-active':''}" data-tag-choice data-id="${h(id)}" data-tag="${h(t.value)}"><span>${h(t.emoji||'')}</span><b>${h(t.label)}</b></button>`).join(''); document.body.appendChild(menu); const rect=button.getBoundingClientRect(); menu.style.left=`${Math.min(window.innerWidth-220,Math.max(8,rect.left))}px`; menu.style.top=`${Math.min(window.innerHeight-260,rect.bottom+8)}px`; openTagMenu=menu; }
function closeTagMenu(){ if(openTagMenu){ openTagMenu.remove(); openTagMenu=null; } }
async function handleAction(actionId,button){ if(actionId.startsWith('group:')) return pullGroup(actionId.slice(6),button); const row=lastGroupedRows.find(r=>String(r.Id)===String(actionId)); if(!row) return setState({status:'Could not find that item.'}); const old=button.textContent; const oldLabel=button.getAttribute('aria-label')||button.title||''; button.classList.add('is-working'); if(button.textContent.trim()) button.textContent='Working'; button.setAttribute('aria-label','Working'); try{ const result=await runItemAction(row); if(result.updatedRow) applyLocalRowUpdates([result.updatedRow], result.message||'Action complete.'); else setState({status:result.message||'Action complete.'}); if(result.needsRefresh) requestRefresh('post-action-refresh'); }catch(err){ setState({status:err.message||String(err)}); } finally{ setTimeout(()=>{ button.classList.remove('is-working'); if(old.trim()) button.textContent=old; if(oldLabel) button.setAttribute('aria-label',oldLabel); },1200); } }
function openGroupCompare(groupKey){ const rows=lastGroupedRows.filter(r=>r.Is_Dupe&&r.GroupActionKey===groupKey).map(addGrade); if(!rows.length) return setState({status:'No duplicate group found to compare.'}); openCompareModal(rows,{onTag:updateTag,onPullGroup:(groupRows,button)=>pullGroup(groupRows[0]?.GroupActionKey||groupKey,button),onPullItem:(row,button)=>handleAction(String(row.Id),button),renderers:{renderStat,renderTotal,renderArmorBonuses,archetypeIcon,tierMarks,baseTotal,currentTotal}}); }
async function pullGroup(groupKey,button){ const rows=lastGroupedRows.filter(r=>r.Is_Dupe&&r.GroupActionKey===groupKey); if(!rows.length) return setState({status:'No group items found.'}); const old=button?.textContent||''; if(button) button.textContent='Pulling'; try{ const result=await runGroupPull(rows); if(result.updatedRows?.length) applyLocalRowUpdates(result.updatedRows,result.message||'Group action complete.'); else setState({status:result.message||'Group action complete.'}); if(result.needsRefresh) requestRefresh('post-group-pull-refresh'); }catch(err){ setState({status:err.message||String(err)}); } finally{ if(button) setTimeout(()=>button.textContent=old,1200); } }
function applyLocalRowUpdates(updatedRows,status){ const byId=new Map(updatedRows.map(row=>[String(row.Id),row])); const rows=state.rows.map(row=>byId.has(String(row.Id))?{...row,...byId.get(String(row.Id))}:row); setState({rows,status}); saveBungieInventory(rows,'optimistic-transfer-location').catch(error=>console.warn('D2AA optimistic cache update failed',error)); }
function requestRefresh(reason){ setTimeout(()=>window.dispatchEvent(new CustomEvent('d2aa:bungie-sync-request',{detail:{reason,background:true}})),1000); }
function getFilteredRowsFrom(rows){ const old=state.rows; state.rows=rows; const result=getFilteredRows(); state.rows=old; return result; }
function syncFilters(){ fill(els.classFilter,CLASS_ORDER,normalizeClassFilter(state.filters.class)); fill(els.slotFilter,['all',...SLOT_ORDER.filter(s=>state.rows.some(r=>r.Slot===s))],state.filters.slot); fill(els.rarityFilter,['all',...[...new Set(state.rows.map(r=>r.Rarity).filter(Boolean))].sort()],state.filters.rarity); }
function syncClassToggle(){ const active=normalizeClassFilter(state.filters.class); els.classToggle?.querySelectorAll('[data-class-filter]').forEach(btn=>{ const cls=normalizeClassFilter(btn.dataset.classFilter); btn.classList.toggle('is-active',cls===active); const b=btn.querySelector('b'); if(b) b.textContent=String(state.rows.filter(r=>rowMatchesClass(r,cls)).length); }); }
function updateSummary(all,shown){ if(els.summaryShown) els.summaryShown.textContent=shown.length; if(els.summaryCached) els.summaryCached.textContent=all.length; if(els.summaryGroups) els.summaryGroups.textContent=new Set(all.filter(r=>r.Is_Dupe).map(r=>r.GroupActionKey)).size; if(els.summaryRecent) els.summaryRecent.textContent=String(getActiveFeedRows(all).length); if(els.summaryClasses) els.summaryClasses.textContent=normalizeClassFilter(state.filters.class); }
function renderChips(){ const chips=[]; if(state.search) chips.push(`Search: ${state.search}`); if(state.filters.slot!=='all') chips.push(`Slot: ${state.filters.slot}`); if(state.filters.rarity!=='all') chips.push(`Rarity: ${state.filters.rarity}`); els.activeChips.innerHTML=chips.map(c=>`<span>${h(c)}</span>`).join(''); }
function fill(select,values,selected){ if(!select) return; select.innerHTML=values.map(v=>`<option value="${h(v)}">${v==='all'?'All':h(v)}</option>`).join(''); select.value=values.includes(selected)?selected:values[0]; }
function addGrade(row){ return {...row, Grade:gradeFor(row).letter, GradeScore:gradeFor(row).score}; }
function gradeFor(row){ const total=baseTotal(row); const top=Math.max(...STAT_KEYS.map(k=>statModel(row,k).base)); const score=Math.round(Math.min(100,total*1.15 + top*1.25 + (row.Is_Dupe?5:0))); const letter=total>=75?'S':total>=72?'A':total>=68?'B':total>=63?'C':total>=58?'D':'F'; return {letter,score}; }
function groupLabel(row){ return String(row.Group || row.Dupe_Group || row.SortGroup || '').match(/^[0-9]+[A-Z]+$/)?.[0] || ''; }
function groupColorClass(row){ return String(row.GroupColor || '').match(/^group-[1-6]$/)?.[0] || ''; }
function displayName(row){ const name=String(row.Name||'').trim(); return name && !name.includes('|') ? name : String(row.Type || row.Slot || 'Unknown Armor'); }
function statModel(row,key){ const parts=bonusParts(row,key); const bonus=parts.reduce((sum,p)=>sum+n(p.value),0); const explicitBase=n(row[`Base${key}`]); const rawCurrent=n(row[`Current${key}`]??row[key]); const useBase=hasValidExplicitBase(row); let base=useBase?explicitBase:Math.max(0,rawCurrent-bonus); let current=rawCurrent || base+bonus; if(current < base+bonus) current=base+bonus; if(!useBase && bonus>0) base=Math.max(0,current-bonus); return {base,current,parts}; }
function hasValidExplicitBase(row){ const explicit=STAT_KEYS.map(k=>n(row[`Base${k}`])); const sum=explicit.reduce((a,b)=>a+b,0); return sum>0 && sum<=75; }
function baseTotal(row){ return STAT_KEYS.reduce((sum,k)=>sum+statModel(row,k).base,0); }
function currentTotal(row){ return STAT_KEYS.reduce((sum,k)=>sum+statModel(row,k).current,0); }
function auditBonus(row,type,key){ return n(row.StatAudit?.bonusBreakdown?.[type]?.[key] ?? row.SocketAudit?.bonusBreakdown?.[type]?.[key]); }
function bonusParts(row,key){ const parts=BONUS_ORDER.map(type=>({type,value:Math.max(n(row[`${cap(type)}Bonus${key}`]),auditBonus(row,type,key))})).filter(p=>p.value>0); const known=parts.reduce((t,p)=>t+p.value,0); const fallback=Math.max(n(row[`StatBonus${key}`]), Math.max(0,n(row[`Current${key}`]??row[key])-n(row[`Base${key}`]))); if(fallback>known) parts.push({type:'other',value:fallback-known}); return parts; }
function totalBonusParts(row){ const byType=BONUS_ORDER.map(type=>({type,value:STAT_KEYS.reduce((t,k)=>t+Math.max(n(row[`${cap(type)}Bonus${k}`]),auditBonus(row,type,k)),0)})).filter(p=>p.value>0); const known=byType.reduce((t,p)=>t+p.value,0); const fallback=Math.max(n(row.StatBonusTotal), currentTotal(row)-baseTotal(row)); if(fallback>known) byType.push({type:'other',value:fallback-known}); return byType; }
function archetypeIcon(row){ const icon=row.ArchetypeIcon?`<img class="archetype-img" src="${h(row.ArchetypeIcon)}" alt="">`:'<span>◇</span>'; return `<span class="archetype-icon-wrap" tabindex="0">${icon}<span class="d2-tooltip"><b>${h(row.Archetype||'Armor Archetype')}</b><em>Archetype</em><p>${h(row.ArchetypeDescription||'Armor archetype bonus.')}</p></span></span>`; }
function renderArmorBonuses(row){ const perks=armorBonuses(row); if(!perks.length) return '<div class="bonus-icons is-empty"><span></span><span></span><span></span></div>'; return `<div class="bonus-icons" aria-label="Armor bonuses and perks">${perks.slice(0,6).map(renderBonusIcon).join('')}</div>`; }
function renderBonusIcon(perk){ const kind=String(perk.kind||'armor').toLowerCase(); const exotic=kind==='exotic'; const set=kind==='set'; const icon=perk.icon?`<img src="${h(perk.icon)}" alt="" loading="lazy" onerror="this.remove()">`:set?'◆':'✦'; const label=set?(perk.label||'Armor Set Bonus'):exotic?'Exotic Perk':'Armor Bonus'; return `<span class="bonus-icon ${exotic?'is-exotic':''} ${set?'is-set-bonus':''}" tabindex="0">${icon}<span class="d2-tooltip"><b>${h(perk.name||label)}</b><em>${h(label)}</em><p>${h(perk.description||'No description available yet.')}</p></span></span>`; }
function armorBonuses(row){
  const out=[];
  const exoticItem=isExoticRow(row);
  if(!exoticItem){
    for(const perk of parsePerks(row.ArmorSetBonuses||row.SetBonuses)) if(isRealSetBonus(perk,row)) out.push({...perk,kind:'set',label:perk.label||setBonusLabelFromText(`${perk.name||''} ${perk.description||''}`)});
    for(const perk of parsePerks(row.ArmorBonuses||row.ArmorPerks||row.Perks)) if(!isExoticOrArchetypePerk(perk,row) && !isRealSetBonus(perk,row)) out.push({...perk,kind:perk.kind||'armor'});
    for(const perk of statAuditSetBonuses(row)) out.push(perk);
  }
  if(exoticItem) out.push({name:row.ExoticPerkName||row.Name||'Exotic Intrinsic',description:row.ExoticDescription||row.ExoticPerkDescription||'Exotic armor perk. Full perk details will show here when Bungie socket perk data is cached.',icon:row.ExoticIcon||'',kind:'exotic'});
  const seen=new Set();
  return out.filter(p=>{ const key=normal(`${p.kind||''}|${p.name||''}|${p.description||''}`); if(!p.name||seen.has(key)) return false; seen.add(key); return true; });
}
function statAuditSetBonuses(row){ if(isExoticRow(row)) return []; const plugs=[...(row.StatAudit?.activePlugs||[]),...(row.SocketAudit?.activePlugs||[])]; return plugs.filter(plug=>isRealSetBonus(plug,row)).map(plug=>({kind:'set',label:setBonusLabelFromText(`${plug.name||''} ${plug.description||''} ${plug.type||''} ${plug.category||''}`),name:plug.name||'Armor Set Bonus',description:plug.description||plug.type||plug.category||'Armor set bonus socket detected.',icon:plug.icon||'',hash:plug.hash||''})); }
function isRealSetBonus(perk,row){ if(!perk || isExoticOrArchetypePerk(perk,row)) return false; const text=`${perk.name||''} ${perk.description||''} ${perk.label||''} ${perk.type||''} ${perk.category||''} ${perk.kind||''}`; return looksLikeSetBonus(text); }
function isExoticOrArchetypePerk(perk,row){ const text=normal(`${perk?.name||''} ${perk?.description||''} ${perk?.label||''} ${perk?.type||''} ${perk?.category||''} ${perk?.kind||''}`); const name=normal(perk?.name); return isExoticRow(row)||text.includes('exotic')||text.includes('intrinsic')||text.includes('archetype')||ARCHETYPE_NAMES.has(name)||name===normal(row.Name)||name===normal(row.Archetype); }
function looksLikeSetBonus(text){ const value=normal(text); const hasSet=value.includes(' set ')||value.startsWith('set ')||value.includes('armor set')||value.includes('setbonus'); const hasBonus=value.includes('bonus')||value.includes('perk')||value.includes('trait')||value.includes('piece')||value.includes('pieces'); return (hasSet&&hasBonus)||value.includes('set bonus')||value.includes('armor set bonus')||value.includes('2 piece')||value.includes('4 piece')||value.includes('two piece')||value.includes('four piece')||value.includes('wearing 2')||value.includes('wearing 4')||value.includes('while wearing')||value.includes('smokejumper'); }
function setBonusLabelFromText(text){ const value=normal(text); if(/\b2\b/.test(value)||value.includes('two')) return '2-Piece Set Bonus'; if(/\b4\b/.test(value)||value.includes('four')) return '4-Piece Set Bonus'; return 'Armor Set Bonus'; }
function parsePerks(value){ if(!value) return []; if(Array.isArray(value)) return value; try{ const parsed=JSON.parse(value); return Array.isArray(parsed)?parsed:[]; }catch{ return []; } }
function tierMarks(row){ const max=5; const tier=Math.max(0,Math.min(max,n(row.Tier||row.GearTier||0))); const color=tier>=5?'gold':tier>=3?'purple':'white'; return Array.from({length:max},(_,i)=>{ const level=max-i; return `<span class="tier-mark tier-color-${color} ${level<=tier?'is-on':''}">◆</span>`; }); }
function locationText(row){ return row.IsEquipped?'Equipped':row.IsInVault?'Vault':'Inventory'; }
function locationChip(location,row){ const key=String(location||'Inventory').toLowerCase(); const label=key==='equipped'?'Equipped':key==='vault'?'Vault':'Inventory'; const action=row?` data-action="${h(row.Id)}"`:''; const move=row?(row.IsInVault?'Pull from Vault':row.IsEquipped?'Push equipped item':'Push to Vault'):label; const icon=locationIcon(label); return `<button type="button" class="location-chip location-${h(key)} is-action"${action} title="${h(label)} · ${h(move)}" aria-label="${h(label)} · ${h(move)}">${icon}</button>`; }
function lockChip(row){ return `<span class="lock-chip" title="Locked in game" aria-label="Locked in game">${lockIcon()}</span>`; }
function lockIcon(){ return '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="6" y="10" width="12" height="10" rx="1.5"/><path d="M8.5 10V7a3.5 3.5 0 017 0v3"/></svg>'; }
function locationIcon(label){ if(label==='Equipped') return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l7 4v5c0 4.5-2.8 7.8-7 9-4.2-1.2-7-4.5-7-9V7l7-4z"/><path d="M8.5 12.2l2.2 2.2 4.9-5"/></svg>'; if(label==='Vault') return '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="6" width="16" height="14" rx="1.5"/><path d="M8 6V4h8v2M9 13h6M12 10v6"/></svg>'; return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 7l7-4 7 4v10l-7 4-7-4V7z"/><path d="M5 7l7 4 7-4M12 11v10"/></svg>'; }
function tagLabel(tag){ const found=TAGS.find(t=>t.value===tag); return h(found?.label||tag); }
function caretIcon(collapsed){ const path=collapsed?'M8 5l6 7-6 7':'M5 8l7 6 7-6'; return `<svg viewBox="0 0 24 24" focusable="false" aria-hidden="true"><path d="${path}"/></svg>`; }
function rarityClass(r){ return String(r||'common').toLowerCase().replace(/[^a-z0-9]/g,''); }
function cap(v){ return String(v).replace(/^./,c=>c.toUpperCase()); }
function n(v){ const x=Number(String(v??'').replace(/[^0-9.-]/g,'')); return Number.isFinite(x)?x:0; }
function pad(v){ return String(n(v)).padStart(2,' '); }
function h(v){ return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
function normal(v){ return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' '); }
function isExoticRow(row){ return normal(row.Rarity)==='exotic'; }
boot();